export const professions = {
  asesor_juridico: 'Asesor Jurídico',
  auxiliar_administrativo: 'Auxiliar Administrativo',
  auxiliar_contable: 'Auxiliar Contable',
  auxiliar_enfermeria: 'Auxiliar De Enfermería',
  auxiliar_mantenimiento: 'Auxiliar De Mantenimiento',
  auxiliar_servicios: 'Auxiliar De Servicios Generales',
  coordinador_academico: 'Coordinador Académico',
  coordinador_compras: 'Coordinador De Compras',
  coordinador_comunicaciones: 'Coordinador De Comunicaciones',
  coordinador_convenio: 'Coordinador De Convenio',
  coordinador_proyectos: 'Coordinador De Proyectos',
  coordinador_talento_humano: 'Coordinador De Talento Humano',
  coordinadora_sgsst: 'Coordinadora De Mejora Y SGSST',
  coordinadora_financiera: 'Coordinadora Gestión Financiera',
  director: 'Director',
  docente: 'Docente Formación Técnica',
  educador_especial: 'Educador Especial',
  educador_fisico: 'Educador Físico',
  enfermero_jefe: 'Enfermero Jefe',
  fisioterapeuta: 'Fisioterapeuta',
  fonoaudiologo: 'Fonoaudiólogo',
  gerontologo: 'Gerontólogo',
  lider_responabilidad: 'Líder De Responsabilidad Social',
  manipulador: 'Manipulador De Alimentos',
  nutricionista: 'Nutricionista',
  psicologo: 'Psicólogo',
  regente: 'Regente De Farmacia',
  revisor_fiscal: 'Revisor Fiscal',
  secretario: 'Secretario',
  tallerista: 'Tallerista',
  tecnico_ambiental: 'Técnico Ambiental',
  tecnico_gastronomia: 'Técnico En Gastronomía',
  tecnico_documental: 'Técnico En Gestión Documental',
  tecnologo_alimentos: 'Tecnólogo En Alimentos',
  terapeuta: 'Terapeuta Ocupacional',
  trabajador_social: 'Trabajador Social',
}